spring:
  application:
    name: im-user
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://47.106.116.106:3306/im_user?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
   username: root
   password: 123456
  profiles:
    active: dev
server:
  port: 9010
mob:
  service:
    url: https://webapi.sms.mob.com/sms/verify
    appkey: 2789337855483
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.106.116.106:1001/eureka/