netty:
  port: 9876
basic:
  client:
    username: acme
    password: acmesecret
spring:
  application:
    name: netty
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.106.116.106:3306/im_user?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.106.116.106:1001/eureka/