netty:
  port: 9876
basic:
  client:
    username: acme
    password: acmesecret
spring:
  application:
    name: nettys
eureka:
  client:
    serviceUrl:
      defaultZone: http://47.106.116.106:1001/eureka/